const { Listing } = require('../models/index.js')
const listingData = [
  {
    "price": 590000,
    "date_created": "2023-08-25",
    "address": "678 Oakridge Rd",
    "postal_code": "M6M 3B3",
    "city": "Toronto",
    "listing_type": "Condo",
    "sqft": 1600,
    "rooms": 3,
    "baths": 2,
    "description": "Contemporary 3-bedroom condo in Toronto with 2 bathrooms and 1600 sqft of modern living space."
  },
  {
    "price": 680000,
    "date_created": "2023-11-05",
    "address": "234 Birchwood Ave",
    "postal_code": "M5S 3K9",
    "city": "Toronto",
    "listing_type": "House",
    "sqft": 2100,
    "rooms": 4,
    "baths": 3,
    "description": "Beautiful 4-bedroom house in Toronto with 3 bathrooms and 2100 sqft of character."
  },
  {
    "price": 750000,
    "date_created": "2023-10-15",
    "address": "567 Elmwood Ln",
    "postal_code": "L6T 1P7",
    "city": "Vaughan",
    "listing_type": "House",
    "sqft": 2500,
    "rooms": 4,
    "baths": 3,
    "description": "Spacious 4-bedroom house in Vaughan with 3 bathrooms and 2500 sqft of living space."
  },
  {
    "price": 610000,
    "date_created": "2023-09-08",
    "address": "321 Willow Ave",
    "postal_code": "L6J 2X4",
    "city": "Oakville",
    "listing_type": "Condo",
    "sqft": 1800,
    "rooms": 3,
    "baths": 2,
    "description": "Elegant 3-bedroom condo in Oakville with 2 bathrooms and 1800 sqft of luxury."
  },
  {
    "price": 920000,
    "date_created": "2023-12-01",
    "address": "789 Cedar Rd",
    "postal_code": "L1T 2M5",
    "city": "Ajax",
    "listing_type": "House",
    "sqft": 3200,
    "rooms": 5,
    "baths": 4,
    "description": "Luxurious 5-bedroom house in Ajax with 4 bathrooms and 3200 sqft of elegance."
  },
  {
    "price": 550000,
    "date_created": "2023-07-12",
    "address": "456 Maple Ave",
    "postal_code": "M4N 1R8",
    "city": "Toronto",
    "listing_type": "House",
    "sqft": 2000,
    "rooms": 4,
    "baths": 2,
    "description": "Charming 4-bedroom house in Toronto with 2 bathrooms and 2000 sqft of character."
  },
  {
    "price": 710000,
    "date_created": "2023-05-20",
    "address": "101 Oakwood Dr",
    "postal_code": "M6S 2E9",
    "city": "Toronto",
    "listing_type": "Condo",
    "sqft": 1700,
    "rooms": 3,
    "baths": 2,
    "description": "Modern 3-bedroom condo in Toronto with 2 bathrooms and 1700 sqft of contemporary living."
  },
  {
    "price": 830000,
    "date_created": "2023-02-28",
    "address": "222 Birch Ave",
    "postal_code": "L6H 1K6",
    "city": "Vaughan",
    "listing_type": "House",
    "sqft": 2800,
    "rooms": 5,
    "baths": 3,
    "description": "Spacious 5-bedroom house in Vaughan with 3 bathrooms and 2800 sqft of living space."
  },
  {
    "price": 620000,
    "date_created": "2023-04-15",
    "address": "333 Elm Ln",
    "postal_code": "L6M 3B9",
    "city": "Oakville",
    "listing_type": "Condo",
    "sqft": 1900,
    "rooms": 3,
    "baths": 2,
    "description": "Cozy 3-bedroom condo in Oakville with 2 bathrooms and 1900 sqft of living space."
  },
  {
    "price": 950000,
    "date_created": "2023-10-25",
    "address": "567 Pine Rd",
    "postal_code": "L1S 3T2",
    "city": "Ajax",
    "listing_type": "House",
    "sqft": 3100,
    "rooms": 6,
    "baths": 4,
    "description": "Stunning 6-bedroom house in Ajax with 4 bathrooms and 3100 sqft of luxurious living space."
  },
  {
    "price": 590000,
    "date_created": "2023-07-05",
    "address": "789 Cedar Ave",
    "postal_code": "M4P 2S7",
    "city": "Toronto",
    "listing_type": "House",
    "sqft": 2300,
    "rooms": 4,
    "baths": 2,
    "description": "Classic 4-bedroom house in Toronto with 2 bathrooms and 2300 sqft of charm."
  },
  {
    "price": 720000,
    "date_created": "2023-09-10",
    "address": "234 Oakwood Ln",
    "postal_code": "M5V 1N9",
    "city": "Toronto",
    "listing_type": "Condo",
    "sqft": 1600,
    "rooms": 3,
    "baths": 2,
    "description": "Elegant 3-bedroom condo in Toronto with 2 bathrooms and 1600 sqft of luxury."
  },
  {
    "price": 760000,
    "date_created": "2023-03-18",
    "address": "345 Birchwood Rd",
    "postal_code": "L6A 2H5",
    "city": "Vaughan",
    "listing_type": "House",
    "sqft": 2400,
    "rooms": 4,
    "baths": 3,
    "description": "Beautiful 4-bedroom house in Vaughan with 3 bathrooms and 2400 sqft of character."
  },
  {
    "price": 610000,
    "date_created": "2023-08-12",
    "address": "567 Maple St",
    "postal_code": "M3R 4K2",
    "city": "Toronto",
    "listing_type": "House",
    "sqft": 2400,
    "rooms": 4,
    "baths": 2,
    "description": "Classic 4-bedroom house in Toronto with 2 bathrooms and 2400 sqft of charm."
  },
  {
    "price": 780000,
    "date_created": "2023-05-30",
    "address": "789 Oakwood Ave",
    "postal_code": "M6C 2V6",
    "city": "Toronto",
    "listing_type": "Condo",
    "sqft": 1700,
    "rooms": 3,
    "baths": 2,
    "description": "Elegant 3-bedroom condo in Toronto with 2 bathrooms and 1700 sqft of luxury."
  },
  {
    "price": 730000,
    "date_created": "2023-11-18",
    "address": "345 Willow Rd",
    "postal_code": "L6P 2T1",
    "city": "Vaughan",
    "listing_type": "House",
    "sqft": 2600,
    "rooms": 5,
    "baths": 3,
    "description": "Spacious 5-bedroom house in Vaughan with 3 bathrooms and 2600 sqft of living space."
  },
  {
    "price": 620000,
    "date_created": "2023-09-02",
    "address": "123 Elmwood Dr",
    "postal_code": "L6J 1B3",
    "city": "Oakville",
    "listing_type": "Condo",
    "sqft": 1900,
    "rooms": 3,
    "baths": 2,
    "description": "Modern 3-bedroom condo in Oakville with 2 bathrooms and 1900 sqft of contemporary living."
  },
  {
    "price": 970000,
    "date_created": "2023-10-10",
    "address": "456 Birchwood Ln",
    "postal_code": "L1S 4T8",
    "city": "Ajax",
    "listing_type": "House",
    "sqft": 3300,
    "rooms": 6,
    "baths": 4,
    "description": "Luxurious 6-bedroom house in Ajax with 4 bathrooms and 3300 sqft of elegance."
  },
  {
    "price": 525000,
    "date_created": "2023-03-10",
    "address": "789 Elm St",
    "postal_code": "M4P 2G8",
    "city": "Toronto",
    "listing_type": "House",
    "sqft": 2200,
    "rooms": 4,
    "baths": 2,
    "description": "Charming 4-bedroom house in Toronto. 2 bathrooms, 2200 sqft of living space."
  },
  {
    "price": 720000,
    "date_created": "2023-06-15",
    "address": "456 Oak Ave",
    "postal_code": "M5V 1N6",
    "city": "Mississauga",
    "listing_type": "Condo",
    "sqft": 1500,
    "rooms": 3,
    "baths": 2,
    "description": "Modern 3-bedroom condo in Mississauga with 2 bathrooms and 1500 sqft of space."
  },
  {
    "price": 820000,
    "date_created": "2023-02-22",
    "address": "101 Pine Rd",
    "postal_code": "L6H 2T9",
    "city": "Vaughan",
    "listing_type": "House",
    "sqft": 2800,
    "rooms": 5,
    "baths": 3,
    "description": "Spacious 5-bedroom house in Vaughan with 3 bathrooms and 2800 sqft of living area."
  },
  {
    "price": 650000,
    "date_created": "2023-04-05",
    "address": "222 Birch Blvd",
    "postal_code": "L6M 1Z2",
    "city": "Oakville",
    "listing_type": "Condo",
    "sqft": 1800,
    "rooms": 3,
    "baths": 2,
    "description": "Cozy 3-bedroom condo in Oakville. 2 bathrooms, 1800 sqft of living space."
  },
  {
    "price": 920000,
    "date_created": "2023-07-20",
    "address": "333 Cedar Ln",
    "postal_code": "L1T 3S7",
    "city": "Ajax",
    "listing_type": "House",
    "sqft": 3200,
    "rooms": 6,
    "baths": 4,
    "description": "Stunning 6-bedroom house in Ajax with 4 bathrooms and 3200 sqft of luxurious living space."
  },
  {
    "price": 1050000,
    "date_created": "2023-12-10",
    "address": "890 Maple St",
    "postal_code": "M4N 3K1",
    "city": "Toronto",
    "listing_type": "House",
    "sqft": 3500,
    "rooms": 6,
    "baths": 4,
    "description": "Luxurious 6-bedroom house in Toronto with 4 bathrooms and 3500 sqft of elegance."
  },
  {
    "price": 1125000,
    "date_created": "2023-10-28",
    "address": "567 Oakridge Ave",
    "postal_code": "M5P 2G5",
    "city": "Toronto",
    "listing_type": "Condo",
    "sqft": 2200,
    "rooms": 4,
    "baths": 3,
    "description": "Elegant 4-bedroom condo in Toronto with 3 bathrooms and 2200 sqft of luxury."
  },
  {
    "price": 1180000,
    "date_created": "2023-11-15",
    "address": "123 Birch Ln",
    "postal_code": "L6H 3T5",
    "city": "Vaughan",
    "listing_type": "House",
    "sqft": 4000,
    "rooms": 7,
    "baths": 5,
    "description": "Spacious 7-bedroom house in Vaughan with 5 bathrooms and 4000 sqft of living space."
  },
  {
    "price": 1250000,
    "date_created": "2023-09-20",
    "address": "456 Willow Rd",
    "postal_code": "L6J 1P9",
    "city": "Oakville",
    "listing_type": "Condo",
    "sqft": 2600,
    "rooms": 5,
    "baths": 4,
    "description": "Modern 5-bedroom condo in Oakville with 4 bathrooms and 2600 sqft of contemporary living."
  },
  {
    "price": 1350000,
    "date_created": "2023-08-02",
    "address": "678 Elmwood Dr",
    "postal_code": "L1T 2B4",
    "city": "Ajax",
    "listing_type": "House",
    "sqft": 4500,
    "rooms": 8,
    "baths": 6,
    "description": "Stunning 8-bedroom house in Ajax with 6 bathrooms and 4500 sqft of luxurious living space."
  },
  {
    "price": 1500000,
    "date_created": "2023-12-18",
    "address": "890 Cedar Ave",
    "postal_code": "M4P 3S9",
    "city": "Toronto",
    "listing_type": "House",
    "sqft": 3800,
    "rooms": 6,
    "baths": 5,
    "description": "Elegant 6-bedroom house in Toronto with 5 bathrooms and 3800 sqft of luxury."
  },
]
const seedListing = () => Listing.bulkCreate(listingData);
module.exports = seedListing;

